name: Deployment To DockerHub

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest   

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
                
      - name: Get short sha
        uses: benjlevesque/short-sha@v2.2    

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REPO_NAME }}:${{ env.SHA }} .
          docker tag ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REPO_NAME }}:${{ env.SHA }} ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REPO_NAME }}:latest
          docker images

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REPO_NAME }}:${{ env.SHA }}
          docker push ${{ secrets.DOCKER_REGISTRY }}/${{ secrets.REPO_NAME }}:latest

      - name: Trigger Event in Argo Repository
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ARGO_PAT }}
          repository: anmaletic/argoapps
          event-type: update-version-pinchat-server
          client-payload: '{"version": "${{ env.SHA }}" }'
